services:

    mdenet-reverse-proxy:
        image: "nginx:latest"
        ports:
            - "8080:80"
        volumes:
            - ./config/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped

    mdenet-educationplatform:
        image: mdenet-educationplatform:latest
        ports:
            - "8081:80"
        environment:
            - TOKEN_SERVER_URL
            - WEBSOCKETS_URI
            - FEEDBACK_SURVEY_URL
        build:
          context: educationplatform
          dockerfile: ./platform/Dockerfile
          args: 
              - TOKEN_SERVER_URL=$TOKEN_SERVER_URL
              - WEBSOCKETS_URI=$WEBSOCKETS_URI
              - FEEDBACK_SURVEY_URL=$FEEDBACK_SURVEY_URL
        volumes:
            - ./config/list-redirect.conf:/etc/nginx/conf.d/default.conf
            - ./public/list.html:/usr/share/nginx/html/list.html
        restart: unless-stopped

    mdenet-tokenserver:
        image: mdenet-tokenserver:latest
        build:
          context: educationplatform
          dockerfile: ./tokenserver/Dockerfile
        ports:
            - "${TS_PORT}:${TS_PORT}"
        environment:
            - TS_PORT
        restart: unless-stopped

    mdenet-test-activities:
        image: "nginx:1.23"
        ports:
            - "8082:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - ./activities:/usr/share/nginx/html
        restart: unless-stopped

    mdenet-tool-conversion:
       image: mde-tool-conversion:latest
       ports:
          - "8069:80"
       build:
         context: platformtools
         dockerfile: static.conversion/Dockerfile

    mdenet-tool-epsilon:
        image: ghcr.io/epsilonlabs/playground-backend/ep-tool-server:epsilon2.8
        ports:
            - "8070:8080"
        restart: unless-stopped

    mdenet-tool-emfatic:
        image: mdenet-tool-emfatic:latest
        ports:
            - "8071:80"
        build:
          context: platformtools
          dockerfile: static.emfatic/Dockerfile
        restart: unless-stopped

    mdenet-tool-ocl:
        image: mdenet-tool-ocl:latest
        ports:
            - "8072:80"
        build:
          context: platformtools
          dockerfile: static.ocl/Dockerfile
        restart: unless-stopped

    mdenet-tool-emf:
        image: mdenet-tool-emf:latest
        ports:
            - "8073:80"
        build:
          context: platformtools
          dockerfile: static.emf/Dockerfile
        restart: unless-stopped
          
    mdenet-tool-xtext:
      image: mdenet-tool-xtext-service:latest
      ports: 
          - 8074:8080
          - 10001:10001
          - 9000:9000
      environment:
          - TRUSTED_ORIGINS
          - ES_DEPLOY_ADDRESS
          - ES_ADDRESS
      build:
          context: platformtools
          dockerfile: xtext/Dockerfile
          args:
              - TRUSTED_ORIGINS=$TRUSTED_ORIGINS
              - ES_ADDRESS=$ES_ADDRESS          
              - ES_DEPLOY_ADDRESS=$ES_DEPLOY_ADDRESS          
      restart: unless-stopped
